#!/usr/bin/env python3

import random
import sys


def checkkey(key):
    key_sum = 0
    for c in key:
        key_sum += ord(c)
    sys.stdout.write("{0:3} | {1}   \r".format(key_sum, key))
    sys.stdout.flush()
    return key_sum


if __name__ == "__main__":
    key = ""

    while True:
        key += random.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
        sum = checkkey(key)
        if sum > 916:
            key = ""
        elif sum == 916:
            print("Found valid key : {0}".format(key))
