#!/usr/bin/env python3

import urllib.request
import json

class bcolors:
   HEADER = '\033[95m'
   OKBLUE = '\033[94m'
   OKGREEN = '\033[92m'
   WARNING = '\033[93m'
   FAIL = '\033[91m'
   ENDC = '\033[0m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'

request = urllib.request.Request('https://api.ipify.org?format=json')
response = urllib.request.urlopen(request)

raw_data = response.read().decode("utf-8")
json_data = json.loads(raw_data)

ipv4 = json_data["ip"]
print("My IPv4: " + bcolors.OKGREEN + ipv4[:] + bcolors.ENDC) 
